version: '3'
services:
  app:
      build: ./docker/app/
      container_name: userservice_app
      volumes:
          - ./:/usr/share/nginx/www
      working_dir: /usr/share/nginx/www
      networks:
        bridge:
          aliases:
          - userservice_app
  nginx:
      build: ./docker/nginx
      container_name: userservice
      links:
          - app
      volumes_from:
          - app
      ports:
          - 81:80
      networks:
        bridge:
          aliases:
          - userservice
networks:
  bridge:
    external:
      name: app_bridge