<?php
/**
 * SearchPostsFilterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ensi\EBSPostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API ServicesPost
 *
 * APi Post
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@greensight.ru
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ensi\EBSPostClient;

use PHPUnit\Framework\TestCase;

/**
 * SearchPostsFilterTest Class Doc Comment
 *
 * @category    Class
 * @description SearchPostsFilter
 * @package     Ensi\EBSPostClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SearchPostsFilterTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchPostsFilter"
     */
    public function testSearchPostsFilter()
    {
    }

    /**
     * Test attribute "rating_gte"
     */
    public function testPropertyRatingGte()
    {
    }

    /**
     * Test attribute "rating_lte"
     */
    public function testPropertyRatingLte()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "tags_like"
     */
    public function testPropertyTagsLike()
    {
    }

    /**
     * Test attribute "text_like"
     */
    public function testPropertyTextLike()
    {
    }

    /**
     * Test attribute "title_like"
     */
    public function testPropertyTitleLike()
    {
    }
}
