<?php
/**
 * PostsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ensi\EBSPostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API ServicesPost
 *
 * APi Post
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@greensight.ru
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ensi\EBSPostClient;

use \Ensi\EBSPostClient\Configuration;
use \Ensi\EBSPostClient\ApiException;
use \Ensi\EBSPostClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PostsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ensi\EBSPostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PostsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPost
     *
     * Создание поста.
     *
     */
    public function testCreatePost()
    {
    }

    /**
     * Test case for createPostVoice
     *
     * Создание голоса поста.
     *
     */
    public function testCreatePostVoice()
    {
    }

    /**
     * Test case for deleteOneVoicePost
     *
     * Удаление одного голоса.
     *
     */
    public function testDeleteOneVoicePost()
    {
    }

    /**
     * Test case for deletePost
     *
     * Удаление одного поста.
     *
     */
    public function testDeletePost()
    {
    }

    /**
     * Test case for deletePostVoices
     *
     * Удаление оценок поста.
     *
     */
    public function testDeletePostVoices()
    {
    }

    /**
     * Test case for getPost
     *
     * Получение одного поста.
     *
     */
    public function testGetPost()
    {
    }

    /**
     * Test case for getPostVoices
     *
     * Получение получение оценок поста.
     *
     */
    public function testGetPostVoices()
    {
    }

    /**
     * Test case for getPosts
     *
     * Получени массив постов.
     *
     */
    public function testGetPosts()
    {
    }

    /**
     * Test case for patchPost
     *
     * Редактирование поста.
     *
     */
    public function testPatchPost()
    {
    }

    /**
     * Test case for patchPostVoice
     *
     * Редактирование голоса.
     *
     */
    public function testPatchPostVoice()
    {
    }

    /**
     * Test case for searchPostVoices
     *
     * Поиск голосов поста.
     *
     */
    public function testSearchPostVoices()
    {
    }

    /**
     * Test case for searchPosts
     *
     * Поиск постов.
     *
     */
    public function testSearchPosts()
    {
    }
}
